RED-457 #time 7h finished RC retrofit web service caller
smartnsoft/droid4me.ws pull request #1
Opened 2018-02-12 16:39 UTC by david-fournier-smartnsoft

2018-03-23 17:47 UTC, ludovicroland requested changes

2018-03-23 17:47 UTC, ludovicroland commented on build.gradle
> +  ext.kotlin_version = '1.1.51'
@david-fournier-smartnsoft : Peux-tu mettre à jour le projet avec une version de Kotlin plus récente STP ?

2018-03-23 17:47 UTC, ludovicroland commented on build.gradle
>      classpath "com.android.tools.build:gradle:2.3.3"
@david-fournier-smartnsoft : Quelle version de d'Android Studio est utilisée ici ? Théoriquement le plugin devrait être en version 3.0.1 tout comme Android Studio. Peux-tu corriger STP ?

2018-03-23 17:47 UTC, ludovicroland commented on retrofit/build.gradle
> +  compileSdkVersion 25
@david-fournier-smartnsoft : Plusieurs choses ici :
* le fichier ne respecte pas la norme des fichiers gradle chez Smart&Soft
* tu utilises des _vieilles_ versions du SDK (25, il faudrait mettre 27 et supprimer la ligne qui concerne les `buildTools`)
* tu utilises une vieille version de gradle (le `compile` devrait laisser sa place au `implementation` ou `api`).
* tu utilises en dépendance des veilles version `droid4me` et `droid4me.ext`

Peux-tu faire une passe sur ce fichier STP ?

2018-03-23 17:47 UTC, ludovicroland commented on retrofit/build.gradle
> +repositories {
@david-fournier-smartnsoft : cette élément est-il vraiment nécessaire ici ?

2018-03-23 17:47 UTC, ludovicroland commented on retrofit/src/main/java/com/smartnsoft/ws/retrofit/RetrofitWebServiceCaller.kt
> + * The class description here.
@david-fournier-smartnsoft : Ce commentaire ne me semble pas pertinent, peux-tu le supprimer STP ?

2018-03-23 17:47 UTC, ludovicroland commented on retrofit/src/main/java/com/smartnsoft/ws/retrofit/RetrofitWebServiceCaller.kt
> +private val ONLY_CACHE_UNSATISFIABLE_ERROR_CODE = 504
@david-fournier-smartnsoft : Si cet élément est une constante, ne devrait-il pas être porté par un `companion object` ? D'ailleurs pourquoi 504 ? Est-ce représentatif d'un code d'erreur HTTP ?

2018-03-23 17:47 UTC, ludovicroland commented on retrofit/src/main/java/com/smartnsoft/ws/retrofit/RetrofitWebServiceCaller.kt
> +package com.smartnsoft.wstest
@david-fournier-smartnsoft : Ce fichier Kotlin ne respecte pas la norme des fichiers Kotlin chez Smart&Soft. Peux-tu revoir le formatage STP ?

2018-03-23 17:47 UTC, ludovicroland commented on retrofit/src/main/java/com/smartnsoft/ws/retrofit/RetrofitWebServiceCaller.kt
> +  inner class CacheInterceptor : Interceptor {
@david-fournier-smartnsoft : Sommes-nous vraiment obligé de travailler avec une `inner class` ? Ne peut-on pas utiliser une `nested class` ? D'ailleurs est-ce que sa visibilité `public` est pertinente ?

2018-03-23 17:47 UTC, ludovicroland commented on retrofit/src/main/java/com/smartnsoft/ws/retrofit/RetrofitWebServiceCaller.kt
> +        .addConverterFactory(JacksonConverterFactory.create())
@david-fournier-smartnsoft : Je ne suis pas forcément d'accord avec ta "politique" d'imposer Jackson et Scalars ici. Tu devrais, selon moi, ne pas proposer Scalars par défaut et proposer une seconde implémentation de ton WebServiceCaller avec Jackson à l'image de ce qui est sur les autres composants (par exemple `okHttpClientWebServiceCaller` et `JacksonOkHttpWebServiceCaller`). 

De plus, tu devrais permettre des points d'ancrages permettant aux personnes qui implémentent de créer leur propre client http et leur propre service (cf les méthode `computeHttpClient` par exemple).

Peux-tu corriger ça STP ?

2018-03-23 17:47 UTC, ludovicroland commented on settings.gradle
> +include ':retrofit'
@david-fournier-smartnsoft : si tu changes le `'` en `"` c'est parfait pour moi :)

2018-03-23 17:48 UTC, ludovicroland commented
@david-fournier-smartnsoft : Peux-tu également joindre une sample app qui tape par exemple ce web-service (https://jsonplaceholder.typicode.com/) en GET, POST, PUT et DELETE pour démontrer l'implémentation et le bon fonctionnement ?

2018-03-26 15:37 UTC, david-fournier-smartnsoft commented on retrofit/src/main/java/com/smartnsoft/ws/retrofit/RetrofitWebServiceCaller.kt
> +private val ONLY_CACHE_UNSATISFIABLE_ERROR_CODE = 504
En vrai je trouve un peu lourd ces companion objects ... Surtout pour une constante privée. Sinon oui c'est une erreur interne de cache utilisée par OkHttp

2018-03-26 15:46 UTC, david-fournier-smartnsoft commented on retrofit/src/main/java/com/smartnsoft/ws/retrofit/RetrofitWebServiceCaller.kt
> +private val ONLY_CACHE_UNSATISFIABLE_ERROR_CODE = 504
Bon finalement je l'ai mis dans le companion object :)

2018-03-26 15:48 UTC, david-fournier-smartnsoft commented on retrofit/src/main/java/com/smartnsoft/ws/retrofit/RetrofitWebServiceCaller.kt
> +  inner class CacheInterceptor : Interceptor {
Je l'avais passée en inner pour le debug log. Je modifie ça.

2018-03-27 08:35 UTC, david-fournier-smartnsoft commented on settings.gradle
> +include ':retrofit'
Fait

2018-03-29 09:32 UTC, david-fournier-smartnsoft commented
Done

2018-03-29 09:32 UTC, david-fournier-smartnsoft commented
Sample app faite et tous les retours pris en compte. Besoin de JavaDoc si accord de principe.

2018-03-30 08:37 UTC, ludovicroland requested changes

2018-03-30 08:37 UTC, ludovicroland commented on build.gradle
> +    maven { url "https://jitpack.io" }
@david-fournier-smartnsoft : A quoi sert Jitpack dans ton cas ?

2018-03-30 08:37 UTC, ludovicroland commented on build.gradle
> +      url "https://jitpack.io"
@david-fournier-smartnsoft : A quoi sert Jitpack dans ton cas ?

2018-03-30 08:37 UTC, ludovicroland commented on okhttp/build.gradle
> +    targetSdkVersion 27
@david-fournier-smartnsoft : Pourquoi avoir modifié les fichiers du module `okhttp` ?

2018-03-30 08:37 UTC, ludovicroland commented on retrofit/build.gradle
> +android {
@david-fournier-smartnsoft : Peux-tu reformater ton fichier pour qu'il respecte le normes des fichiers gradles chez Smart&Soft STP ?

2018-03-30 08:37 UTC, ludovicroland commented on retrofit/src/main/java/com/smartnsoft/ws/retrofit/RetrofitWebServiceCaller.kt
> +abstract class RetrofitWebServiceCaller<out API>(api: Class<API>, baseUrl: String, private val connectTimeout: Long = CONNECT_TIMEOUT, private val readTimeout: Long = READ_TIMEOUT, private val writeT
@david-fournier-smartnsoft : Je pense qu'on a oublié une dernière chose pour cette classe. Il faudrait ajouter un `Boolean` `isConnected` dans ta classe qu'un `ConnectivityListener` peut, par exemple, mettre à jour. Dans le cas où cet attribut a pour valeur `false`, il convient que ton composant ne tente même pas la requête et jette une erreur de type `UnknownHostException`. Ça permet de pas faire des tentatives pour rien.

Tu peux implémenter cette logique STP ?

Autre chose, est-ce que tu as bien plugguer ton ton système sur les erreurs de droid4me à savoir :
* `CallException`
* `CacheException`
* `JacksonParsingException`

Tu peux vérifier STP ? Ca facilitera les migrations :)

2018-03-30 08:37 UTC, ludovicroland commented on retrofit/src/main/java/com/smartnsoft/ws/retrofit/RetrofitWebServiceCaller.kt
> +  private val httpClient: OkHttpClient by lazy {
@david-fournier-smartnsoft : C'est du détail, mais pour moi tu peux mettre tout ça sur une ligne comme tu as fait au dessus :)

2018-03-30 08:37 UTC, ludovicroland commented on retrofit/src/main/java/com/smartnsoft/ws/retrofit/RetrofitWebServiceCaller.kt
> +    const val CONNECT_TIMEOUT = 10 * 1000L        // 10 s
@david-fournier-smartnsoft : Un petit saut de ligne entre les déclarations des constantes pour faire respirer tout ça ? 😇

2018-03-30 08:37 UTC, ludovicroland commented on retrofitsample/build.gradle
> +android {
@david-fournier-smartnsoft : Peux-tu formater ton fichier pour qu'il respecte les normes des fichiers Smart&Soft STP ?

2018-03-30 08:37 UTC, ludovicroland commented on retrofitsample/build.gradle
> +  implementation ("com.android.support:appcompat-v7:27.0.2")
@david-fournier-smartnsoft : Quitte à proposer une _sample app_, peux-tu mettre en dépendance des versions à jour des bibliothèques ? la dernière est la `27.1.0`

2018-03-30 08:37 UTC, ludovicroland commented on retrofitsample/src/main/AndroidManifest.xml
> +<manifest xmlns:android="http://schemas.android.com/apk/res/android"
@david-fournier-smartnsoft : Je sais que je suis un peu chiant avec ça, mais peux-tu formater ton fichier pour qu'il respecte la norme des fichiers XML ? :D

2018-03-30 08:37 UTC, ludovicroland commented on retrofitsample/src/main/java/com/smartnsoft/retrofitsample/MainActivity.kt
> +class MainActivity : AppCompatActivity()
@david-fournier-smartnsoft : Tant que Kotlin ne propose pas le réarrangement de code automatique, on doit faire attention. Dans ton cas, la syntaxe de l'héritage ne respecte pas la norme des fichiers Smart&Soft. Peux-tu corriger STP ?

2018-03-30 08:37 UTC, ludovicroland commented on retrofitsample/src/main/java/com/smartnsoft/retrofitsample/MainActivity.kt
> +class MainActivity : AppCompatActivity()
@david-fournier-smartnsoft : A noter que cette classe est du Kotlin. Tu peux la déplacer dans un dossier `kotlin` STP ?

2018-03-30 08:37 UTC, ludovicroland commented on retrofitsample/src/main/java/com/smartnsoft/retrofitsample/ws/MyWebServiceCaller.kt
> +  lateinit var context: Context
@david-fournier-smartnsoft : c'est vilain ça. Retenir un `Context` dans un classe qui implémente le _pattern_ singleton c'est pas fou.

Je suppose que c'est en lien avec ton `cacheDir`. Ne peux-tu pas trouver une solution alternative ?

2018-03-30 08:37 UTC, ludovicroland commented on retrofitsample/src/main/java/com/smartnsoft/retrofitsample/ws/WSApi.kt
> +    val url = "http://httpbin.org/"
@david-fournier-smartnsoft : `val const` ne serait-il pas mieux ?

2018-03-30 09:52 UTC, david-fournier-smartnsoft commented on retrofitsample/src/main/java/com/smartnsoft/retrofitsample/ws/WSApi.kt
> +    val url = "http://httpbin.org/"
Si

2018-03-30 12:03 UTC, david-fournier-smartnsoft commented on retrofitsample/src/main/java/com/smartnsoft/retrofitsample/MainActivity.kt
> +class MainActivity : AppCompatActivity()
Yep done

2018-03-30 12:04 UTC, david-fournier-smartnsoft commented on retrofitsample/src/main/AndroidManifest.xml
> +<manifest xmlns:android="http://schemas.android.com/apk/res/android"
Fait

2018-03-30 12:06 UTC, david-fournier-smartnsoft commented on retrofitsample/build.gradle
> +  implementation ("com.android.support:appcompat-v7:27.0.2")
fait

2018-03-30 12:07 UTC, david-fournier-smartnsoft commented on retrofit/build.gradle
> +android {
fait

2018-03-30 12:07 UTC, david-fournier-smartnsoft commented on okhttp/build.gradle
> +    targetSdkVersion 27
reverted

2018-03-30 12:07 UTC, david-fournier-smartnsoft commented on build.gradle
> +      url "https://jitpack.io"
enlevé

2018-03-30 12:07 UTC, david-fournier-smartnsoft commented on build.gradle
> +    maven { url "https://jitpack.io" }
enlevé

2018-03-30 12:07 UTC, david-fournier-smartnsoft commented on retrofit/src/main/java/com/smartnsoft/ws/retrofit/RetrofitWebServiceCaller.kt
> +abstract class RetrofitWebServiceCaller<out API>(api: Class<API>, baseUrl: String, private val connectTimeout: Long = CONNECT_TIMEOUT, private val readTimeout: Long = READ_TIMEOUT, private val writeT
Pour CallException et CacheException c'est fait déjà. J'attaque le reste

2018-03-30 12:23 UTC, david-fournier-smartnsoft commented on retrofit/src/main/java/com/smartnsoft/ws/retrofit/RetrofitWebServiceCaller.kt
> +abstract class RetrofitWebServiceCaller<out API>(api: Class<API>, baseUrl: String, private val connectTimeout: Long = CONNECT_TIMEOUT, private val readTimeout: Long = READ_TIMEOUT, private val writeT
Je ne trouve nulle part JacksonParsingException

2018-03-30 12:52 UTC, david-fournier-smartnsoft commented on retrofit/src/main/java/com/smartnsoft/ws/retrofit/RetrofitWebServiceCaller.kt
> +abstract class RetrofitWebServiceCaller<out API>(api: Class<API>, baseUrl: String, private val connectTimeout: Long = CONNECT_TIMEOUT, private val readTimeout: Long = READ_TIMEOUT, private val writeT
fait

2018-03-30 13:47 UTC, david-fournier-smartnsoft commented on retrofitsample/src/main/java/com/smartnsoft/retrofitsample/ws/MyWebServiceCaller.kt
> +  lateinit var context: Context
fait

2018-03-30 13:49 UTC, ludovicroland approved these changes

2018-03-30 13:51 UTC, merged